name: release
on:
  create:
    branches:
    - master
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  release:
    runs-on: ubuntu-latest
    if: "github.event.ref_type == 'tag'"
    steps:
    - name: setup go
      uses: actions/setup-go@v2
      with:
        go-version: 1.x
    - name: checkout
      uses: actions/checkout@v2
    - name: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        make release
