name: tagpr
on:
  push:
    branches:
    - "main"
  workflow_dispatch:
permissions:
  actions: read
  artifact-metadata: write
  attestations: write
  contents: write
  id-token: write
  pull-requests: write
  issues: write
jobs:
  tagpr:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: setup go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version-file: go.mod
    - name: tagpr
      id: tagpr
      uses: Songmu/tagpr@7ebae2dcc300132baa7cc9dd108c8923b07fc366 # v1.20.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: ./.github/actions/release
      with:
        tag: ${{ steps.tagpr.outputs.tag }}
        token: ${{ secrets.GITHUB_TOKEN }}
      if: "steps.tagpr.outputs.tag != ''"
